<?php

/**
 * 5/27/15
 *
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */


$sumEven = 0;
$current = 0;
$lastNum = 0;

while (true) {
    if ($lastNum == 0) {
        $lastNum++;
        $current = 2;
    } else {
        $temp    = $current;
        $current = $current + $lastNum;
        $lastNum = $temp;
    }

    if ($current % 2 == 0 && $current <= 4000000) {
        $sumEven += $current;
    } elseif ($current > 4000000) {
        break;
    }
}

echo 'Answer: '.$sumEven;
